In [386]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime

original_crime_df = pd.read_csv("Crime_Data_from_2020_to_Present 2.csv")
print(original_crime_df.head())
print(original_crime_df['Crm Cd'].value_counts()[:10])
new_dataset = original_crime_df[original_crime_df["Crm Cd"].isin([510,624,740,330,310,230,626,440,420,354]) ]
new_dataset.head()

       DR_NO               Date Rptd                DATE OCC  TIME OCC  AREA  \
0   10304468  01/08/2020 12:00:00 AM  01/08/2020 12:00:00 AM      2230     3   
1  190101086  01/02/2020 12:00:00 AM  01/01/2020 12:00:00 AM       330     1   
2  201220752  09/16/2020 12:00:00 AM  09/16/2020 12:00:00 AM      1230    12   
3  191501505  01/01/2020 12:00:00 AM  01/01/2020 12:00:00 AM      1730    15   
4  191921269  01/01/2020 12:00:00 AM  01/01/2020 12:00:00 AM       415    19   

     AREA NAME  Rpt Dist No  Part 1-2  Crm Cd  \
0    Southwest          377         2     624   
1      Central          163         2     624   
2  77th Street         1259         2     745   
3  N Hollywood         1543         2     745   
4      Mission         1998         2     740   

                                         Crm Cd Desc  ... Status  Status Desc  \
0                           BATTERY - SIMPLE ASSAULT  ...     AO  Adult Other   
1                           BATTERY - SIMPLE ASSAULT  ...     

DR_NO               Date Rptd                DATE OCC  TIME OCC  AREA  \
0    10304468  01/08/2020 12:00:00 AM  01/08/2020 12:00:00 AM      2230     3   
1   190101086  01/02/2020 12:00:00 AM  01/01/2020 12:00:00 AM       330     1   
4   191921269  01/01/2020 12:00:00 AM  01/01/2020 12:00:00 AM       415    19   
10  200100509  01/04/2020 12:00:00 AM  01/04/2020 12:00:00 AM      2200     1   
15  201811813  05/28/2020 12:00:00 AM  05/25/2020 12:00:00 AM       200    18   

    AREA NAME  Rpt Dist No  Part 1-2  Crm Cd  \
0   Southwest          377         2     624   
1     Central          163         2     624   
4     Mission         1998         2     740   
10    Central          192         1     330   
15  Southeast         1851         1     510   

                                          Crm Cd Desc  ... Status  \
0                            BATTERY - SIMPLE ASSAULT  ...     AO   
1                            BATTERY - SIMPLE ASSAULT  ...     IC   
4   VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...  ...     IC   
10                              BURGLARY FROM VEHICLE  ...     IC   
15                                   VEHICLE - STOLEN  ...     IC   

    Status Desc Crm Cd 1 Crm Cd 2  Crm Cd 3 Crm Cd 4  \
0   Adult Other    624.0      NaN       NaN      NaN   
1   Invest Cont    624.0      NaN       NaN      NaN   
4   Invest Cont    740.0      NaN       NaN      NaN   
10  Invest Cont    330.0      NaN       NaN      NaN   
15  Invest Cont    510.0      NaN       NaN      NaN   

                                    LOCATION                     Cross Street  \
0    1100 W  39TH                         PL                              NaN   
1     700 S  HILL                         ST                              NaN   
4   14400    TITUS                        ST                              NaN   
10                                      15TH                            OLIVE   
15           MENLO                        AV  130TH                        ST   

        LAT       LON  
0   34.0141 -118.2978  
1   34.0459 -118.2545  
4   34.2198 -118.4468  
10  34.0359 -118.2648  
15  33.9144 -118.2894  

[5 rows x 28 columns]

In [387]:
dataset_510 = original_crime_df[original_crime_df["Crm Cd"].isin([510]) ]
dataset_624 = original_crime_df[original_crime_df["Crm Cd"].isin([624])]
dataset_740 = original_crime_df[original_crime_df["Crm Cd"].isin([740])]
dataset_330 = original_crime_df[original_crime_df["Crm Cd"].isin([330])]
dataset_310 = original_crime_df[original_crime_df["Crm Cd"].isin([310])]
dataset_230 = original_crime_df[original_crime_df["Crm Cd"].isin([230])]
dataset_626 = original_crime_df[original_crime_df["Crm Cd"].isin([626])]
dataset_440 = original_crime_df[original_crime_df["Crm Cd"].isin([440])]
dataset_420 = original_crime_df[original_crime_df["Crm Cd"].isin([420])]
dataset_354 = original_crime_df[original_crime_df["Crm Cd"].isin([354])]


dataset_510


DR_NO               Date Rptd                DATE OCC  TIME OCC  \
15      201811813  05/28/2020 12:00:00 AM  05/25/2020 12:00:00 AM       200   
24      201713253  09/15/2020 12:00:00 AM  09/14/2020 12:00:00 AM      1305   
27      200505212  01/29/2020 12:00:00 AM  01/26/2020 12:00:00 AM      1200   
32      200117988  09/15/2020 12:00:00 AM  09/03/2020 12:00:00 AM      2000   
50      201312607  06/21/2020 12:00:00 AM  06/21/2020 12:00:00 AM        30   
...           ...                     ...                     ...       ...   
317802  210911274  07/05/2021 12:00:00 AM  07/03/2021 12:00:00 AM      1900   
317808  211204656  01/11/2021 12:00:00 AM  01/10/2021 12:00:00 AM      2300   
317846  210404776  01/21/2021 12:00:00 AM  01/19/2021 12:00:00 AM      1600   
317849  211208872  03/19/2021 12:00:00 AM  03/19/2021 12:00:00 AM      1105   
317853  212005847  02/22/2021 12:00:00 AM  02/22/2021 12:00:00 AM      1200   

        AREA    AREA NAME  Rpt Dist No  Part 1-2  Crm Cd       Crm Cd Desc  \
15        18    Southeast         1851         1     510  VEHICLE - STOLEN   
24        17   Devonshire         1776         1     510  VEHICLE - STOLEN   
27         5       Harbor          529         1     510  VEHICLE - STOLEN   
32         1      Central          111         1     510  VEHICLE - STOLEN   
50        13       Newton         1321         1     510  VEHICLE - STOLEN   
...      ...          ...          ...       ...     ...               ...   
317802     9     Van Nuys          911         1     510  VEHICLE - STOLEN   
317808    12  77th Street         1259         1     510  VEHICLE - STOLEN   
317846     4   Hollenbeck          497         1     510  VEHICLE - STOLEN   
317849    12  77th Street         1218         1     510  VEHICLE - STOLEN   
317853    20      Olympic         2034         1     510  VEHICLE - STOLEN   

        ... Status  Status Desc Crm Cd 1 Crm Cd 2  Crm Cd 3 Crm Cd 4  \
15      ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
24      ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
27      ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
32      ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
50      ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
...     ...    ...          ...      ...      ...       ...      ...   
317802  ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
317808  ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
317846  ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
317849  ...     IC  Invest Cont    510.0      NaN       NaN      NaN   
317853  ...     IC  Invest Cont    510.0      NaN       NaN      NaN   

                                        LOCATION  \
15               MENLO                        AV   
24      16700    LABRADOR                     ST   
27                                             E   
32        500 N  FIGUEROA                     ST   
50        100 E  24TH                         ST   
...                                          ...   
317802  15600    VANOWEN                      ST   
317808    400 E  74TH                         ST   
317846   1400 S  DE LA TORRE                  WY   
317849           58TH                         ST   
317853   3300 W  8TH                          ST   

                           Cross Street      LAT       LON  
15      130TH                        ST  33.9144 -118.2894  
24                                  NaN  34.2493 -118.4965  
27                                BROAD  33.7753 -118.2456  
32                                  NaN  34.0615 -118.2470  
50                                  NaN  34.0266 -118.2676  
...                                 ...      ...       ...  
317802                              NaN  34.1939 -118.4732  
317808                              NaN  33.9730 -118.2657  
317846                              NaN  34.0166 -118.2058  
317849  FIGUEROA          

In [388]:
dataset_510['Date Rptd'] = pd.to_datetime(dataset_510['Date Rptd'])
dataset_510['DATE OCC'] = pd.to_datetime(dataset_510['DATE OCC'])

dataset_510.sort_values(by="DATE OCC")


/var/folders/8g/z0__2mts0rnbjh3kq8zsfz2w0000gn/T/ipykernel_6830/4109199034.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/8g/z0__2mts0rnbjh3kq8zsfz2w0000gn/T/ipykernel_6830/4109199034.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



DR_NO  Date Rptd   DATE OCC  TIME OCC  AREA    AREA NAME  \
15061   201604004 2020-01-01 2020-01-01         5    16     Foothill   
9729    201104043 2020-01-02 2020-01-01      1830    11    Northeast   
9728    201104038 2020-01-01 2020-01-01       800    11    Northeast   
1434    200204057 2020-01-02 2020-01-01      2000     2      Rampart   
1432    200204055 2020-01-02 2020-01-01      2200     2      Rampart   
...           ...        ...        ...       ...   ...          ...   
292740  211011359 2021-08-16 2021-08-16       705    10  West Valley   
317434  211815272 2021-08-16 2021-08-16       400    18    Southeast   
201876  210115282 2021-08-16 2021-08-16      1900     1      Central   
277674  211711552 2021-08-16 2021-08-16       510    17   Devonshire   
296769  211416655 2021-08-16 2021-08-16       130    14      Pacific   

        Rpt Dist No  Part 1-2  Crm Cd       Crm Cd Desc  ... Status  \
15061          1601         1     510  VEHICLE - STOLEN  ...     IC   
9729           1145         1     510  VEHICLE - STOLEN  ...     IC   
9728           1149         1     510  VEHICLE - STOLEN  ...     IC   
1434            204         1     510  VEHICLE - STOLEN  ...     IC   
1432            275         1     510  VEHICLE - STOLEN  ...     IC   
...             ...       ...     ...               ...  ...    ...   
292740         1049         1     510  VEHICLE - STOLEN  ...     IC   
317434         1823         1     510  VEHICLE - STOLEN  ...     IC   
201876          138         1     510  VEHICLE - STOLEN  ...     IC   
277674         1794         1     510  VEHICLE - STOLEN  ...     IC   
296769         1414         1     510  VEHICLE - STOLEN  ...     IC   

        Status Desc Crm Cd 1 Crm Cd 2  Crm Cd 3 Crm Cd 4  \
15061   Invest Cont    510.0      NaN       NaN      NaN   
9729    Invest Cont    510.0      NaN       NaN      NaN   
9728    Invest Cont    510.0      NaN       NaN      NaN   
1434    Invest Cont    510.0      NaN       NaN      NaN   
1432    Invest Cont    510.0      NaN       NaN      NaN   
...             ...      ...      ...       ...      ...   
292740  Invest Cont    510.0      NaN       NaN      NaN   
317434  Invest Cont    510.0      NaN       NaN      NaN   
201876  Invest Cont    510.0      NaN       NaN      NaN   
277674  Invest Cont    510.0      NaN       NaN      NaN   
296769  Invest Cont    510.0      NaN       NaN      NaN   

                                        LOCATION  \
15061   11900    COMETA                       AV   
9729     2500    GLENDALE                     BL   
9728                            100 S  AVENUE 57   
1434     3400    PLATA                        ST   
1432                                  BURLINGTON   
...                                          ...   
292740   6300    BALBOA                       BL   
317434  10100 S  SAN PEDRO                    ST   
201876           BOYD                         ST   
277674  18500    PARTHENIA                    ST   
296769    700    INDIANA                      AV   

                           Cross Street      LAT       LON  
15061                               NaN  34.2866 -118.4125  
9729                                NaN  34.1027 -118.2592  
9728                                NaN  34.1074 -118.1978  
1434                                NaN  34.0777 -118.2821  
1432                       JAMES M WOOD  34.0519 -118.2755  
...                                 ...      ...       ...  
292740                              NaN   0.0000    0.0000  
317434                              NaN  33.9438 -118.2695  
201876  WALL                         ST   0.0000    0.0000  
277674                              NaN  34.2282 -118.5367  
296769                              NaN  33.9975 -118.4670  

[34216 rows x 28 columns]

In [389]:
df1 = dataset_510['DATE OCC'].dt.date.value_counts().sort_index().reset_index()
df1.columns = ['DATE','Count']

df1['DATE'] = pd.to_datetime(df1['DATE']) - pd.to_timedelta(7, unit='d')
df1= df1.groupby([pd.Grouper(key='DATE', freq='W')])['Count'].sum()

df1 = pd.DataFrame(data=df1.values, columns=['Count'])
df1 = df1.values
df1 = df1.astype('int32')
df1
# df1 = dataset_510['DATE OCC'].dt.date.value_counts().sort_index().reset_index()
# df1.columns = ['DATE','Count']
# # df1.plot(x='DATE',y='Count')
# dataset_510.groupby([pd.Grouper(key='DATE OCC', freq='W')]).count()

array([[194],
       [344],
       [308],
       [317],
       [342],
       [312],
       [310],
       [306],
       [306],
       [322],
       [336],
       [307],
       [361],
       [412],
       [415],
       [412],
       [442],
       [394],
       [450],
       [413],
       [436],
       [400],
       [459],
       [468],
       [495],
       [514],
       [522],
       [431],
       [438],
       [438],
       [442],
       [414],
       [421],
       [382],
       [429],
       [384],
       [374],
       [388],
       [372],
       [387],
       [415],
       [382],
       [438],
       [411],
       [410],
       [409],
       [423],
       [397],
       [414],
       [403],
       [391],
       [385],
       [416],
       [400],
       [407],
       [442],
       [433],
       [484],
       [458],
       [466],
       [411],
       [435],
       [408],
       [391],
       [393],
       [408],
       [386],
       [398],
       [441],
       [460],
       [405],
      

In [390]:
# def alignObjectHTML():
#     display(HTML("""<style>#output-body {display: flex;align-items: center;justify-content: center;}</style>"""))
def formatNumber(n):
    return '{:,}'.format(n).replace(","," ")
def highlight_diag(df):
    a = np.full(df.shape, '', dtype='<U24')
    np.fill_diagonal(a, 'background-color: yellow')
    return pd.DataFrame(a, index=df.index, columns=df.columns)
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [391]:
import plotly.graph_objects as go
list_graphs = []
graph_1 = go.Scatter(x=list(range(0,len(df1))),y=df1.flatten(),name="Dataset")
list_graphs.append(graph_1)
average = moving_average(df1)
graph_2 = go.Scatter(x=list(range(0,len(df1))),y=average,name="Average")
list_graphs.append(graph_2)
fig = go.Figure(data=list_graphs)
fig.update_layout(width=1024,height=500,title="Dataset of crimes in ",xaxis=dict(title='Weeks'),yaxis=dict(title='Number of crimes'))

fig.show()

In [392]:
from sklearn.preprocessing import RobustScaler , MinMaxScaler
#
scaler = MinMaxScaler()
df1 = scaler.fit_transform(df1)

In [393]:
# dataset_510['DATE OCC'] = pd.to_datetime(dataset_510['DATE OCC']) - pd.to_timedelta(7, unit='d')

df1
train_size = int(len(df1) * 0.7)
print(train_size)
test_size = len(df1) - train_size
print(test_size)
train, test = df1[0:train_size,:], df1[train_size:len(df1),:]

# df1 = df1.drop(['DATE'], axis=1, index=None, columns=None, level=None, inplace=False, errors='raise')\

60
26


In [394]:
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back):
        a = dataset[i:(i+look_back),0]
        dataX.append(a)
        dataY.append(dataset[i + look_back,0])
    return np.array(dataX), np.array(dataY)

In [395]:
# I make my dataset
look_back = 1
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)

In [396]:
trainX.shape, trainY.shape, testX.shape, testY.shape

((59, 1), (59,), (25, 1), (25,))

In [397]:
trainX = np.reshape(trainX, (trainX.shape[0],1, trainX.shape[1]))
testX = np.reshape(testX, (testX.shape[0],1, testX.shape[1]))
# trainX.shape

In [398]:

from keras.models import Sequential
from keras.layers import Dense, LSTM



model = Sequential()
model.add(LSTM(8,activation='tanh',return_sequences=True, input_shape=(1,look_back)))
model.add(LSTM(4,activation='tanh',return_sequences=False, input_shape=(1,look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='rmsprop')
model.fit(trainX, trainY, epochs=500, batch_size=4, verbose=1)

Epoch 1/500
15/15 [==============================] - 1s 1ms/step - loss: 0.5559
Epoch 2/500
15/15 [==============================] - 0s 968us/step - loss: 0.4923
Epoch 3/500
15/15 [==============================] - 0s 1ms/step - loss: 0.4360
Epoch 4/500
15/15 [==============================] - 0s 970us/step - loss: 0.3794
Epoch 5/500
15/15 [==============================] - 0s 1ms/step - loss: 0.3228
Epoch 6/500
15/15 [==============================] - 0s 1ms/step - loss: 0.2660
Epoch 7/500
15/15 [==============================] - 0s 812us/step - loss: 0.2114
Epoch 8/500
15/15 [==============================] - 0s 775us/step - loss: 0.1603
Epoch 9/500
15/15 [==============================] - 0s 792us/step - loss: 0.1141
Epoch 10/500
15/15 [==============================] - 0s 804us/step - loss: 0.0751
Epoch 11/500
15/15 [==============================] - 0s 793us/step - loss: 0.0448
Epoch 12/500
15/15 [==============================] - 0s 785us/step - loss: 0.0230
Epoch 13/500
15/15 [=

In [399]:
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

1/1 [==============================] - 0s 7ms/step


In [400]:
trainPredict.shape, trainY.shape
# trainPredict
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])

In [401]:
trainY[0],trainPredict[:,0]

(array([344., 308., 317., 342., 312., 310., 306., 306., 322., 336., 307.,
        361., 412., 415., 412., 442., 394., 450., 413., 436., 400., 459.,
        468., 495., 514., 522., 431., 438., 438., 442., 414., 421., 382.,
        429., 384., 374., 388., 372., 387., 415., 382., 438., 411., 410.,
        409., 423., 397., 414., 403., 391., 385., 416., 400., 407., 442.,
        433., 484., 458., 466.]),
 array([269.48358, 369.388  , 343.83994, 350.14734, 367.94724, 346.63635,
        345.2368 , 342.4459 , 342.4459 , 353.67517, 363.63937, 343.1426 ,
        381.72717, 419.60953, 421.87183, 419.60953, 442.3654 , 406.1077 ,
        448.47714, 420.36325, 437.7924 , 410.59396, 455.3708 , 462.2808 ,
        483.08447, 497.7634 , 503.94717, 433.9893 , 439.3156 , 439.3156 ,
        442.3654 , 421.11743, 426.406  , 397.182  , 432.47015, 398.66507,
        391.26852, 401.63684, 389.79498, 400.8932 , 421.87183, 397.182  ,
        439.3156 , 418.85614, 418.10312, 417.35046, 427.92007, 408.34894,
    

In [402]:
testY[0],testPredict[:,0]

(array([435., 408., 391., 393., 408., 386., 398., 441., 460., 405., 405.,
        405., 433., 405., 422., 415., 412., 433., 410., 368., 390., 429.,
        367., 382.,  23.]),
 array([418.85614, 437.0312 , 416.59818, 403.87033, 405.36145, 416.59818,
        400.15002, 409.09683, 441.6025 , 456.13776, 414.34366, 414.34366,
        414.34366, 435.50967, 414.34366, 427.16293, 421.87183, 419.60953,
        435.50967, 418.10312, 386.854  , 403.12537, 432.47015, 386.12006,
        397.182  ], dtype=float32))

In [403]:
from skimage.metrics import mean_squared_error
import math
trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
print('Test Score: %.2f RMSE' % (testScore))

Train Score: 31.75 RMSE
Test Score: 79.22 RMSE


In [404]:
trainPredictPlot = np.empty_like(df1)
trainPredictPlot[:, :] = np.nan
trainPredictPlot[look_back:len(trainPredict)+look_back, :] = trainPredict

In [405]:
testPredictPlot = np.empty_like(df1)
testPredictPlot[:, :] = np.nan
testPredictPlot[len(trainPredict)+(look_back):len(df1)-1, :] = testPredict

In [406]:
listGraph = []
listGraph.append(go.Scatter(x=list(range(0,len(df1))),y=scaler.inverse_transform(df1).flatten(),name="Original dataset"))
listGraph.append(go.Scatter(x=list(range(0,len(trainPredictPlot))),y=trainPredictPlot.flatten(),name="Predict with Train set"))
listGraph.append(go.Scatter(x=list(range(0,len(testPredictPlot))),y=testPredictPlot.flatten(),name="Predict with Train set"))

fig = go.Figure(data=listGraph)
fig.update_layout(width=1024,height=500,title="[LSTM] Prediction for ",xaxis=dict(title='Month'),yaxis=dict(title='Number of crimes'))

fig.show()

In [407]:
dataset_624

DR_NO               Date Rptd                DATE OCC  TIME OCC  \
0        10304468  01/08/2020 12:00:00 AM  01/08/2020 12:00:00 AM      2230   
1       190101086  01/02/2020 12:00:00 AM  01/01/2020 12:00:00 AM       330   
16      201707577  03/20/2020 12:00:00 AM  03/20/2020 12:00:00 AM      1320   
68      200104054  01/02/2020 12:00:00 AM  01/01/2020 12:00:00 AM      2330   
70      200104058  01/02/2020 12:00:00 AM  01/01/2020 12:00:00 AM      1940   
...           ...                     ...                     ...       ...   
317819  210407038  03/25/2021 12:00:00 AM  03/25/2021 12:00:00 AM      1015   
317838  210206530  03/05/2021 12:00:00 AM  03/05/2021 12:00:00 AM       915   
317842  210610209  05/25/2021 12:00:00 AM  05/25/2021 12:00:00 AM       813   
317848  212110947  07/04/2021 12:00:00 AM  07/04/2021 12:00:00 AM      2135   
317851  211710505  07/09/2021 12:00:00 AM  07/09/2021 12:00:00 AM      1050   

        AREA   AREA NAME  Rpt Dist No  Part 1-2  Crm Cd  \
0          3   Southwest          377         2     624   
1          1     Central          163         2     624   
16        17  Devonshire         1752         2     624   
68         1     Central          135         2     624   
70         1     Central          135         2     624   
...      ...         ...          ...       ...     ...   
317819     4  Hollenbeck          497         2     624   
317838     2     Rampart          246         2     624   
317842     6   Hollywood          645         2     624   
317848    21     Topanga         2143         2     624   
317851    17  Devonshire         1798         2     624   

                     Crm Cd Desc  ... Status  Status Desc Crm Cd 1 Crm Cd 2  \
0       BATTERY - SIMPLE ASSAULT  ...     AO  Adult Other    624.0      NaN   
1       BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
16      BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
68      BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
70      BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
...                          ...  ...    ...          ...      ...      ...   
317819  BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
317838  BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
317842  BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
317848  BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   
317851  BATTERY - SIMPLE ASSAULT  ...     IC  Invest Cont    624.0      NaN   

        Crm Cd 3 Crm Cd 4                                  LOCATION  \
0            NaN      NaN   1100 W  39TH                         PL   
1            NaN      NaN    700 S  HILL                         ST   
16           NaN      NaN  20900    DEVONSHIRE                   ST   
68           NaN      NaN                                      WALL   
70           NaN      NaN           LOS ANGELES                  ST   
...          ...      ...                                       ...   
317819       NaN      NaN   3400    EMERY                        ST   
317838       NaN      NaN    600 S  ALVARADO                     ST   
317842       NaN      NaN   6800    HOLLYWOOD                    BL   
317848       NaN      NaN  23100    FRIAR                        ST   
317851       NaN      NaN   8800    DEMPSEY                      AV   

                           Cross Street      LAT       LON  
0                                   NaN  34.0141 -118.2978  
1                                   NaN  34.0459 -118.2545  
16                                  NaN  34.2572 -118.5885  
68      5TH                          ST  34.0495 -118.2458  
70      2ND                          ST  34.0485 -118.2447  
...                                 ...      ...       ...  
317819                              NaN  34.0153 -118.2061  
317838                              NaN  34.0593 -118.2750  
317

In [420]:
dataset_624['Date Rptd'] = pd.to_datetime(dataset_624['Date Rptd'])
dataset_624['DATE OCC'] = pd.to_datetime(dataset_624['DATE OCC'])

dataset_624.sort_values(by="DATE OCC")


/var/folders/8g/z0__2mts0rnbjh3kq8zsfz2w0000gn/T/ipykernel_6830/2874154411.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/8g/z0__2mts0rnbjh3kq8zsfz2w0000gn/T/ipykernel_6830/2874154411.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



DR_NO  Date Rptd   DATE OCC  TIME OCC  AREA    AREA NAME  \
4310    200504040 2020-01-01 2020-01-01      1250     5       Harbor   
13022   201404017 2020-01-01 2020-01-01       330    14      Pacific   
13021   201404016 2020-01-01 2020-01-01       330    14      Pacific   
12831   201305897 2020-02-03 2020-01-01       700    13       Newton   
179578  201104029 2020-01-01 2020-01-01       930    11    Northeast   
...           ...        ...        ...       ...   ...          ...   
230438  210614359 2021-08-16 2021-08-16       900     6    Hollywood   
276600  211416681 2021-08-16 2021-08-16       935    14      Pacific   
226343  211513215 2021-08-16 2021-08-16      1534    15  N Hollywood   
201090  210115277 2021-08-16 2021-08-16      1110     1      Central   
296880  212112693 2021-08-16 2021-08-16      1420    21      Topanga   

        Rpt Dist No  Part 1-2  Crm Cd               Crm Cd Desc  ... Status  \
4310            589         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
13022          1436         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
13021          1436         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
12831          1367         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
179578         1102         2     624  BATTERY - SIMPLE ASSAULT  ...     AA   
...             ...       ...     ...                       ...  ...    ...   
230438          646         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
276600         1402         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
226343         1566         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
201090          166         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   
296880         2156         2     624  BATTERY - SIMPLE ASSAULT  ...     IC   

         Status Desc Crm Cd 1 Crm Cd 2  Crm Cd 3 Crm Cd 4  \
4310     Invest Cont    624.0      NaN       NaN      NaN   
13022    Invest Cont    624.0      NaN       NaN      NaN   
13021    Invest Cont    624.0      NaN       NaN      NaN   
12831    Invest Cont    624.0      NaN       NaN      NaN   
179578  Adult Arrest    624.0      NaN       NaN      NaN   
...              ...      ...      ...       ...      ...   
230438   Invest Cont    624.0      NaN       NaN      NaN   
276600   Invest Cont    624.0      NaN       NaN      NaN   
226343   Invest Cont    624.0      NaN       NaN      NaN   
201090   Invest Cont    624.0      NaN       NaN      NaN   
296880   Invest Cont    624.0      NaN       NaN      NaN   

                                        LOCATION  \
4310     3700    STEPHEN M WHITE              DR   
13022   11200    WESTMINSTER                  AV   
13021   11200    WESTMINSTER                  AV   
12831    5100    HOLMES                       AV   
179578   4000    PERLITA                      AV   
...                                          ...   
230438                                     SELMA   
276600           SAWTELLE                     BL   
226343   4400    LANKERSHIM                   BL   
201090    400 E  7TH                          ST   
296880   6600    TOPANGA CANYON               BL   

                           Cross Street      LAT       LON  
4310                                NaN  33.7105 -118.2860  
13022                               NaN  34.0172 -118.4230  
13021                               NaN  34.0172 -118.4230  
12831                               NaN  33.9962 -118.2411  
179578                              NaN  34.1254 -118.2648  
...                                 ...      ...       ...  
230438                           CASSIL  34.0998 -118.3338  
276600  NATIONAL                     BL  34.0266 -118.4317  
226343                              NaN   0.0000    0.0000  
201090                              NaN   0.0000    0.0000  
296880                              NaN   0.0000    0.0000  

[25965 rows x 28 columns]

In [421]:
df1 = dataset_624['DATE OCC'].dt.date.value_counts().sort_index().reset_index()
df1.columns = ['DATE','Count']

df1['DATE'] = pd.to_datetime(df1['DATE']) - pd.to_timedelta(7, unit='d')
df1= df1.groupby([pd.Grouper(key='DATE', freq='W')])['Count'].sum()

df1 = pd.DataFrame(data=df1.values, columns=['Count'])
df1 = df1.values
df1 = df1.astype('int32')
df1
# df1 = dataset_510['DATE OCC'].dt.date.value_counts().sort_index().reset_index()
# df1.columns = ['DATE','Count']
# # df1.plot(x='DATE',y='Count')
# dataset_510.groupby([pd.Grouper(key='DATE OCC', freq='W')]).count()

array([[266],
       [335],
       [332],
       [351],
       [360],
       [354],
       [353],
       [328],
       [350],
       [383],
       [314],
       [288],
       [247],
       [260],
       [229],
       [277],
       [303],
       [332],
       [313],
       [273],
       [325],
       [267],
       [276],
       [322],
       [362],
       [345],
       [329],
       [297],
       [344],
       [360],
       [340],
       [329],
       [330],
       [366],
       [325],
       [313],
       [302],
       [332],
       [304],
       [324],
       [291],
       [314],
       [308],
       [268],
       [283],
       [294],
       [302],
       [275],
       [274],
       [277],
       [286],
       [245],
       [254],
       [241],
       [260],
       [279],
       [243],
       [285],
       [268],
       [279],
       [268],
       [288],
       [243],
       [269],
       [292],
       [313],
       [276],
       [258],
       [270],
       [283],
       [293],
      

In [422]:
import plotly.graph_objects as go
list_graphs = []
graph_1 = go.Scatter(x=list(range(0,len(df1))),y=df1.flatten(),name="Dataset")
list_graphs.append(graph_1)
average = moving_average(df1)
graph_2 = go.Scatter(x=list(range(0,len(df1))),y=average,name="Average")
list_graphs.append(graph_2)
fig = go.Figure(data=list_graphs)
fig.update_layout(width=1024,height=500,title="Dataset of crimes in ",xaxis=dict(title='Weeks'),yaxis=dict(title='Number of crimes'))

fig.show()

In [423]:

scaler = MinMaxScaler()
df1 = scaler.fit_transform(df1)

In [429]:
# dataset_510['DATE OCC'] = pd.to_datetime(dataset_510['DATE OCC']) - pd.to_timedelta(7, unit='d')

df1
train_size = int(len(df1) * 0.7)
print(train_size)
test_size = len(df1) - train_size
print(test_size)
train, test = df1[0:train_size,:], df1[train_size:len(df1),:]

# df1 = df1.drop(['DATE'], axis=1, index=None, columns=None, level=None, inplace=False, errors='raise')\

60
26


In [430]:
# dataset_510['DATE OCC'] = pd.to_datetime(dataset_510['DATE OCC']) - pd.to_timedelta(7, unit='d')
look_back = 1
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)

# df1 = df1.drop(['DATE'], axis=1, index=None, columns=None, level=None, inplace=False, errors='raise')\

In [431]:
trainX.shape, trainY.shape, testX.shape, testY.shape

((59, 1), (59,), (25, 1), (25,))

In [432]:
trainX = np.reshape(trainX, (trainX.shape[0],1, trainX.shape[1]))
testX = np.reshape(testX, (testX.shape[0],1, testX.shape[1]))
# trainX.shape

In [433]:

from keras.models import Sequential
from keras.layers import Dense, LSTM



model = Sequential()
model.add(LSTM(8,activation='tanh',return_sequences=True, input_shape=(1,look_back)))
model.add(LSTM(4,activation='tanh',return_sequences=False, input_shape=(1,look_back)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='rmsprop')
model.fit(trainX, trainY, epochs=500, batch_size=4, verbose=1)

Epoch 1/500
15/15 [==============================] - 1s 1ms/step - loss: 0.5604
Epoch 2/500
15/15 [==============================] - 0s 829us/step - loss: 0.5039
Epoch 3/500
15/15 [==============================] - 0s 844us/step - loss: 0.4536
Epoch 4/500
15/15 [==============================] - 0s 909us/step - loss: 0.4023
Epoch 5/500
15/15 [==============================] - 0s 976us/step - loss: 0.3493
Epoch 6/500
15/15 [==============================] - 0s 916us/step - loss: 0.2957
Epoch 7/500
15/15 [==============================] - 0s 714us/step - loss: 0.2430
Epoch 8/500
15/15 [==============================] - 0s 768us/step - loss: 0.1914
Epoch 9/500
15/15 [==============================] - 0s 765us/step - loss: 0.1427
Epoch 10/500
15/15 [==============================] - 0s 700us/step - loss: 0.0995
Epoch 11/500
15/15 [==============================] - 0s 753us/step - loss: 0.0636
Epoch 12/500
15/15 [==============================] - 0s 776us/step - loss: 0.0357
Epoch 13/500
15

In [434]:
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

1/1 [==============================] - 0s 8ms/step


In [435]:
trainPredict.shape, trainY.shape
# trainPredict
trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])

In [436]:
trainY[0],trainPredict[:,0]

(array([335., 332., 351., 360., 354., 353., 328., 350., 383., 314., 288.,
        247., 260., 229., 277., 303., 332., 313., 273., 325., 267., 276.,
        322., 362., 345., 329., 297., 344., 360., 340., 329., 330., 366.,
        325., 313., 302., 332., 304., 324., 291., 314., 308., 268., 283.,
        294., 302., 275., 274., 277., 286., 245., 254., 241., 260., 279.,
        243., 285., 268., 279.]),
 array([278.11978, 324.06467, 322.08618, 334.56403, 340.42587, 336.52173,
        335.86957, 319.44394, 333.91064, 355.23596, 310.16183, 292.82504,
        265.44806, 274.113  , 253.51051, 285.47192, 302.83875, 322.08618,
        309.49704, 282.79785, 317.45917, 278.78787, 284.8034 , 315.47192,
        341.7238 , 330.6378 , 320.10495, 298.83624, 329.9821 , 340.42587,
        327.35562, 320.10495, 320.76566, 344.31412, 317.45917, 309.49704,
        302.172  , 322.08618, 303.50534, 316.79703, 294.82953, 310.16183,
        306.17014, 279.45605, 289.4831 , 296.83328, 302.172  , 284.13483,
    

In [437]:
testY[0],testPredict[:,0]

(array([288., 243., 269., 292., 313., 276., 258., 270., 283., 293., 296.,
        312., 307., 314., 342., 338., 312., 387., 353., 357., 353., 338.,
        338., 288.,  11.]),
 array([279.45605, 292.82504, 262.78818, 280.12433, 295.49756, 309.49704,
        284.8034 , 272.77826, 280.79266, 289.4831 , 296.16547, 298.16867,
        308.83203, 305.5042 , 310.16183, 328.66956, 326.04025, 308.83203,
        357.78403, 335.86957, 338.47574, 335.86957, 326.04025, 326.04025,
        292.82504], dtype=float32))

In [438]:

trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
print('Test Score: %.2f RMSE' % (testScore))

Train Score: 27.07 RMSE
Test Score: 61.41 RMSE


In [439]:
trainPredictPlot = np.empty_like(df1)
trainPredictPlot[:, :] = np.nan
trainPredictPlot[look_back:len(trainPredict)+look_back, :] = trainPredict

In [440]:
testPredictPlot = np.empty_like(df1)
testPredictPlot[:, :] = np.nan
testPredictPlot[len(trainPredict)+(look_back):len(df1)-1, :] = testPredict

In [441]:
listGraph = []
listGraph.append(go.Scatter(x=list(range(0,len(df1))),y=scaler.inverse_transform(df1).flatten(),name="Original dataset"))
listGraph.append(go.Scatter(x=list(range(0,len(trainPredictPlot))),y=trainPredictPlot.flatten(),name="Predict with Train set"))
listGraph.append(go.Scatter(x=list(range(0,len(testPredictPlot))),y=testPredictPlot.flatten(),name="Predict with Train set"))

fig = go.Figure(data=listGraph)
fig.update_layout(width=1024,height=500,title="[LSTM] Prediction for ",xaxis=dict(title='Month'),yaxis=dict(title='Number of crimes'))

fig.show()